[package]
name = "plaia-language"
version = "0.1.0"
authors = ["Alexander Bakst <abakst@cs.ucsd.edu>"]
edition = "2018"

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"

[build-dependencies] # <-- We added this and everything after!
lalrpop = { version = "0.19.0", features = ["lexer"] }
